/*
 * Animal Rescue API
 *
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// Gets or Sets HalfHourMilitaryTimeSelect
        /// </summary>
        public enum HalfHourMilitaryTimeSelect
        { 
            /// <summary>
            /// Enum _0000Enum for "00:00"
            /// </summary>
            [EnumMember(Value = "00:00")]
            _0000Enum = 1,
            
            /// <summary>
            /// Enum _0030Enum for "00:30"
            /// </summary>
            [EnumMember(Value = "00:30")]
            _0030Enum = 2,
            
            /// <summary>
            /// Enum _0100Enum for "01:00"
            /// </summary>
            [EnumMember(Value = "01:00")]
            _0100Enum = 3,
            
            /// <summary>
            /// Enum _0130Enum for "01:30"
            /// </summary>
            [EnumMember(Value = "01:30")]
            _0130Enum = 4,
            
            /// <summary>
            /// Enum _0200Enum for "02:00"
            /// </summary>
            [EnumMember(Value = "02:00")]
            _0200Enum = 5,
            
            /// <summary>
            /// Enum _0230Enum for "02:30"
            /// </summary>
            [EnumMember(Value = "02:30")]
            _0230Enum = 6,
            
            /// <summary>
            /// Enum _0300Enum for "03:00"
            /// </summary>
            [EnumMember(Value = "03:00")]
            _0300Enum = 7,
            
            /// <summary>
            /// Enum _0330Enum for "03:30"
            /// </summary>
            [EnumMember(Value = "03:30")]
            _0330Enum = 8,
            
            /// <summary>
            /// Enum _0400Enum for "04:00"
            /// </summary>
            [EnumMember(Value = "04:00")]
            _0400Enum = 9,
            
            /// <summary>
            /// Enum _0430Enum for "04:30"
            /// </summary>
            [EnumMember(Value = "04:30")]
            _0430Enum = 10,
            
            /// <summary>
            /// Enum _0500Enum for "05:00"
            /// </summary>
            [EnumMember(Value = "05:00")]
            _0500Enum = 11,
            
            /// <summary>
            /// Enum _0530Enum for "05:30"
            /// </summary>
            [EnumMember(Value = "05:30")]
            _0530Enum = 12,
            
            /// <summary>
            /// Enum _0600Enum for "06:00"
            /// </summary>
            [EnumMember(Value = "06:00")]
            _0600Enum = 13,
            
            /// <summary>
            /// Enum _0630Enum for "06:30"
            /// </summary>
            [EnumMember(Value = "06:30")]
            _0630Enum = 14,
            
            /// <summary>
            /// Enum _0700Enum for "07:00"
            /// </summary>
            [EnumMember(Value = "07:00")]
            _0700Enum = 15,
            
            /// <summary>
            /// Enum _0730Enum for "07:30"
            /// </summary>
            [EnumMember(Value = "07:30")]
            _0730Enum = 16,
            
            /// <summary>
            /// Enum _0800Enum for "08:00"
            /// </summary>
            [EnumMember(Value = "08:00")]
            _0800Enum = 17,
            
            /// <summary>
            /// Enum _0830Enum for "08:30"
            /// </summary>
            [EnumMember(Value = "08:30")]
            _0830Enum = 18,
            
            /// <summary>
            /// Enum _0900Enum for "09:00"
            /// </summary>
            [EnumMember(Value = "09:00")]
            _0900Enum = 19,
            
            /// <summary>
            /// Enum _0930Enum for "09:30"
            /// </summary>
            [EnumMember(Value = "09:30")]
            _0930Enum = 20,
            
            /// <summary>
            /// Enum _1000Enum for "10:00"
            /// </summary>
            [EnumMember(Value = "10:00")]
            _1000Enum = 21,
            
            /// <summary>
            /// Enum _1030Enum for "10:30"
            /// </summary>
            [EnumMember(Value = "10:30")]
            _1030Enum = 22,
            
            /// <summary>
            /// Enum _1100Enum for "11:00"
            /// </summary>
            [EnumMember(Value = "11:00")]
            _1100Enum = 23,
            
            /// <summary>
            /// Enum _1130Enum for "11:30"
            /// </summary>
            [EnumMember(Value = "11:30")]
            _1130Enum = 24,
            
            /// <summary>
            /// Enum _1200Enum for "12:00"
            /// </summary>
            [EnumMember(Value = "12:00")]
            _1200Enum = 25,
            
            /// <summary>
            /// Enum _1230Enum for "12:30"
            /// </summary>
            [EnumMember(Value = "12:30")]
            _1230Enum = 26,
            
            /// <summary>
            /// Enum _1300Enum for "13:00"
            /// </summary>
            [EnumMember(Value = "13:00")]
            _1300Enum = 27,
            
            /// <summary>
            /// Enum _1330Enum for "13:30"
            /// </summary>
            [EnumMember(Value = "13:30")]
            _1330Enum = 28,
            
            /// <summary>
            /// Enum _1400Enum for "14:00"
            /// </summary>
            [EnumMember(Value = "14:00")]
            _1400Enum = 29,
            
            /// <summary>
            /// Enum _1430Enum for "14:30"
            /// </summary>
            [EnumMember(Value = "14:30")]
            _1430Enum = 30,
            
            /// <summary>
            /// Enum _1500Enum for "15:00"
            /// </summary>
            [EnumMember(Value = "15:00")]
            _1500Enum = 31,
            
            /// <summary>
            /// Enum _1530Enum for "15:30"
            /// </summary>
            [EnumMember(Value = "15:30")]
            _1530Enum = 32,
            
            /// <summary>
            /// Enum _1600Enum for "16:00"
            /// </summary>
            [EnumMember(Value = "16:00")]
            _1600Enum = 33,
            
            /// <summary>
            /// Enum _1630Enum for "16:30"
            /// </summary>
            [EnumMember(Value = "16:30")]
            _1630Enum = 34,
            
            /// <summary>
            /// Enum _1700Enum for "17:00"
            /// </summary>
            [EnumMember(Value = "17:00")]
            _1700Enum = 35,
            
            /// <summary>
            /// Enum _1730Enum for "17:30"
            /// </summary>
            [EnumMember(Value = "17:30")]
            _1730Enum = 36,
            
            /// <summary>
            /// Enum _1800Enum for "18:00"
            /// </summary>
            [EnumMember(Value = "18:00")]
            _1800Enum = 37,
            
            /// <summary>
            /// Enum _1830Enum for "18:30"
            /// </summary>
            [EnumMember(Value = "18:30")]
            _1830Enum = 38,
            
            /// <summary>
            /// Enum _1900Enum for "19:00"
            /// </summary>
            [EnumMember(Value = "19:00")]
            _1900Enum = 39,
            
            /// <summary>
            /// Enum _1930Enum for "19:30"
            /// </summary>
            [EnumMember(Value = "19:30")]
            _1930Enum = 40,
            
            /// <summary>
            /// Enum _2000Enum for "20:00"
            /// </summary>
            [EnumMember(Value = "20:00")]
            _2000Enum = 41,
            
            /// <summary>
            /// Enum _2030Enum for "20:30"
            /// </summary>
            [EnumMember(Value = "20:30")]
            _2030Enum = 42,
            
            /// <summary>
            /// Enum _2100Enum for "21:00"
            /// </summary>
            [EnumMember(Value = "21:00")]
            _2100Enum = 43,
            
            /// <summary>
            /// Enum _2130Enum for "21:30"
            /// </summary>
            [EnumMember(Value = "21:30")]
            _2130Enum = 44,
            
            /// <summary>
            /// Enum _2200Enum for "22:00"
            /// </summary>
            [EnumMember(Value = "22:00")]
            _2200Enum = 45,
            
            /// <summary>
            /// Enum _2230Enum for "22:30"
            /// </summary>
            [EnumMember(Value = "22:30")]
            _2230Enum = 46,
            
            /// <summary>
            /// Enum _2300Enum for "23:00"
            /// </summary>
            [EnumMember(Value = "23:00")]
            _2300Enum = 47,
            
            /// <summary>
            /// Enum _2330Enum for "23:30"
            /// </summary>
            [EnumMember(Value = "23:30")]
            _2330Enum = 48
        }
}
