/*
 * Animal Rescue API
 *
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// List of allowable Intake types describing how an animal came to the Rescue
        /// </summary>
        /// <value>List of allowable Intake types describing how an animal came to the Rescue</value>
        public enum IntakeType
        { 
            /// <summary>
            /// Enum OwnerSurrenderEnum for "Owner Surrender"
            /// </summary>
            [EnumMember(Value = "Owner Surrender")]
            OwnerSurrenderEnum = 1,
            
            /// <summary>
            /// Enum FailedAdoptionEnum for "Failed Adoption"
            /// </summary>
            [EnumMember(Value = "Failed Adoption")]
            FailedAdoptionEnum = 2,
            
            /// <summary>
            /// Enum StraySurrenderEnum for "Stray Surrender"
            /// </summary>
            [EnumMember(Value = "Stray Surrender")]
            StraySurrenderEnum = 3,
            
            /// <summary>
            /// Enum AbandondedAtRescueEnum for "Abandonded at Rescue"
            /// </summary>
            [EnumMember(Value = "Abandonded at Rescue")]
            AbandondedAtRescueEnum = 4,
            
            /// <summary>
            /// Enum ShelterTransferEnum for "Shelter Transfer"
            /// </summary>
            [EnumMember(Value = "Shelter Transfer")]
            ShelterTransferEnum = 5
        }
}
