/*
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// Gets or Sets MedicalEventType
        /// </summary>
        public enum MedicalEventType
        { 
            /// <summary>
            /// Enum PlacedInIsolationEnum for "Placed in Isolation"
            /// </summary>
            [EnumMember(Value = "Placed in Isolation")]
            PlacedInIsolationEnum = 1,
            
            /// <summary>
            /// Enum RemovedFromIsolationEnum for "Removed from Isolation"
            /// </summary>
            [EnumMember(Value = "Removed from Isolation")]
            RemovedFromIsolationEnum = 2,
            
            /// <summary>
            /// Enum PreventativeEnum for "Preventative"
            /// </summary>
            [EnumMember(Value = "Preventative")]
            PreventativeEnum = 3,
            
            /// <summary>
            /// Enum VaccinationEnum for "Vaccination"
            /// </summary>
            [EnumMember(Value = "Vaccination")]
            VaccinationEnum = 4,
            
            /// <summary>
            /// Enum SurgeryEnum for "Surgery"
            /// </summary>
            [EnumMember(Value = "Surgery")]
            SurgeryEnum = 5
        }
}
