/*
 * Animal Rescue API
 *
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// Gets or Sets PhoneNumberType
        /// </summary>
        public enum PhoneNumberType
        { 
            /// <summary>
            /// Enum HomeEnum for "Home"
            /// </summary>
            [EnumMember(Value = "Home")]
            HomeEnum = 1,
            
            /// <summary>
            /// Enum WorkEnum for "Work"
            /// </summary>
            [EnumMember(Value = "Work")]
            WorkEnum = 2,
            
            /// <summary>
            /// Enum MobileEnum for "Mobile"
            /// </summary>
            [EnumMember(Value = "Mobile")]
            MobileEnum = 3,
            
            /// <summary>
            /// Enum FaxEnum for "Fax"
            /// </summary>
            [EnumMember(Value = "Fax")]
            FaxEnum = 4,
            
            /// <summary>
            /// Enum CustomEnum for "Custom"
            /// </summary>
            [EnumMember(Value = "Custom")]
            CustomEnum = 5
        }
}
