/*
 * Animal Rescue API
 *
 * AnimalRescue CQRS API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlgartee@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// Gets or Sets YearSelect
        /// </summary>
        public enum YearSelect
        { 
            /// <summary>
            /// Enum _2000Enum for "2000"
            /// </summary>
            [EnumMember(Value = "2000")]
            _2000Enum = 1,
            
            /// <summary>
            /// Enum _2001Enum for "2001"
            /// </summary>
            [EnumMember(Value = "2001")]
            _2001Enum = 2,
            
            /// <summary>
            /// Enum _2002Enum for "2002"
            /// </summary>
            [EnumMember(Value = "2002")]
            _2002Enum = 3,
            
            /// <summary>
            /// Enum _2003Enum for "2003"
            /// </summary>
            [EnumMember(Value = "2003")]
            _2003Enum = 4,
            
            /// <summary>
            /// Enum _2004Enum for "2004"
            /// </summary>
            [EnumMember(Value = "2004")]
            _2004Enum = 5,
            
            /// <summary>
            /// Enum _2005Enum for "2005"
            /// </summary>
            [EnumMember(Value = "2005")]
            _2005Enum = 6,
            
            /// <summary>
            /// Enum _2006Enum for "2006"
            /// </summary>
            [EnumMember(Value = "2006")]
            _2006Enum = 7,
            
            /// <summary>
            /// Enum _2007Enum for "2007"
            /// </summary>
            [EnumMember(Value = "2007")]
            _2007Enum = 8,
            
            /// <summary>
            /// Enum _2008Enum for "2008"
            /// </summary>
            [EnumMember(Value = "2008")]
            _2008Enum = 9,
            
            /// <summary>
            /// Enum _2009Enum for "2009"
            /// </summary>
            [EnumMember(Value = "2009")]
            _2009Enum = 10,
            
            /// <summary>
            /// Enum _2010Enum for "2010"
            /// </summary>
            [EnumMember(Value = "2010")]
            _2010Enum = 11,
            
            /// <summary>
            /// Enum _2011Enum for "2011"
            /// </summary>
            [EnumMember(Value = "2011")]
            _2011Enum = 12,
            
            /// <summary>
            /// Enum _2012Enum for "2012"
            /// </summary>
            [EnumMember(Value = "2012")]
            _2012Enum = 13,
            
            /// <summary>
            /// Enum _2013Enum for "2013"
            /// </summary>
            [EnumMember(Value = "2013")]
            _2013Enum = 14,
            
            /// <summary>
            /// Enum _2014Enum for "2014"
            /// </summary>
            [EnumMember(Value = "2014")]
            _2014Enum = 15,
            
            /// <summary>
            /// Enum _2015Enum for "2015"
            /// </summary>
            [EnumMember(Value = "2015")]
            _2015Enum = 16,
            
            /// <summary>
            /// Enum _2016Enum for "2016"
            /// </summary>
            [EnumMember(Value = "2016")]
            _2016Enum = 17,
            
            /// <summary>
            /// Enum _2017Enum for "2017"
            /// </summary>
            [EnumMember(Value = "2017")]
            _2017Enum = 18,
            
            /// <summary>
            /// Enum _2018Enum for "2018"
            /// </summary>
            [EnumMember(Value = "2018")]
            _2018Enum = 19,
            
            /// <summary>
            /// Enum _2019Enum for "2019"
            /// </summary>
            [EnumMember(Value = "2019")]
            _2019Enum = 20,
            
            /// <summary>
            /// Enum _2020Enum for "2020"
            /// </summary>
            [EnumMember(Value = "2020")]
            _2020Enum = 21,
            
            /// <summary>
            /// Enum _2021Enum for "2021"
            /// </summary>
            [EnumMember(Value = "2021")]
            _2021Enum = 22,
            
            /// <summary>
            /// Enum _2022Enum for "2022"
            /// </summary>
            [EnumMember(Value = "2022")]
            _2022Enum = 23,
            
            /// <summary>
            /// Enum _2023Enum for "2023"
            /// </summary>
            [EnumMember(Value = "2023")]
            _2023Enum = 24,
            
            /// <summary>
            /// Enum _2024Enum for "2024"
            /// </summary>
            [EnumMember(Value = "2024")]
            _2024Enum = 25,
            
            /// <summary>
            /// Enum _2025Enum for "2025"
            /// </summary>
            [EnumMember(Value = "2025")]
            _2025Enum = 26,
            
            /// <summary>
            /// Enum _2026Enum for "2026"
            /// </summary>
            [EnumMember(Value = "2026")]
            _2026Enum = 27,
            
            /// <summary>
            /// Enum _2027Enum for "2027"
            /// </summary>
            [EnumMember(Value = "2027")]
            _2027Enum = 28,
            
            /// <summary>
            /// Enum _2028Enum for "2028"
            /// </summary>
            [EnumMember(Value = "2028")]
            _2028Enum = 29,
            
            /// <summary>
            /// Enum _2029Enum for "2029"
            /// </summary>
            [EnumMember(Value = "2029")]
            _2029Enum = 30,
            
            /// <summary>
            /// Enum _2030Enum for "2030"
            /// </summary>
            [EnumMember(Value = "2030")]
            _2030Enum = 31
        }
}
